#ifndef HAZE_INTERMEDIATETYPE_H
#define HAZE_INTERMEDIATETYPE_H

// Haze IntermediateType.h
// (c) Connor J. Link. All Rights Reserved.

#define AS_CALL_FUNCTION_COMMAND(x) static_cast<CallFunctionCommand*>(x)

namespace hz
{
	enum class IntermediateType
	{
		BRANCH_LABEL,
		ENTER_SCOPE,
		LEAVE_SCOPE,
		LOCAL_VARIABLE,
		GLOBAL_VARIABLE,
		HEAP_READ,
		HEAP_WRITE,
		STACK_READ,
		STACK_WRITE,
		ADD,
		SUBTRACT,
		BITOR,
		BITAND,
		BITXOR,
		INCREMENT,
		DECREMENT,
		COPY,
		MAKE_IMMEDIATE,
		MAKE_ARGUMENT,
		TAKE_ARGUMENT,
		CALL_FUNCTION,
		VOID_RETURN,
		VALUE_RETURN,
		IF_NOT_ZERO,
		IF_ZERO,
		GOTO,
		MAKE_MESSAGE,
		PRINT_MESSAGE,
		PRINT_NUMBER,
		EXIT_PROGRAM,
		INLINE_ASSEMBLY,
	};
}

#endif 
