// Haze IntermediateKind.x
// (c) Connor J. Link. All Rights Reserved.

X(ALLOCATE_STACK, allocate)
X(DEREFERENCE, dereference)
X(REFERENCE, reference)
X(IMMEDIATE, immediate)
X(COPY, copy)
X(BINARY, binary)
X(UNARY, unary)
X(COMPARE, compare)
X(BRANCH, branch)
X(CALL, call)
X(RETURN, return)
X(SIGN_EXTEND, signextend)
X(ZERO_EXTEND, zeroextend)
X(TRUNCATE, truncate)
X(REINTERPRET, reinterpret)
X(CAST, cast)
X(OFFSETOF, offset-of)
X(LABEL, label)
