[package]
name = "debugger"
version = "1.0.0"
edition = "2024"

[lib]
name = "debugger"
path = "source/lib.rs"
crate-type = ["staticlib"]

[dependencies]
windows = { version = "0.61.3", features = [
	"Win32_Foundation",
	"Win32_System_Diagnostics_Debug",
	"Win32_System_Diagnostics_Debug_Extensions",
	"Win32_System_Diagnostics_ToolHelp",
	"Win32_System_ProcessStatus",
	"Win32_System_Threading",
	"Win32_Globalization"
] }
